source 'https://rubygems.org'
gem 'watir'
gem 'watir-scroll'
gem 'cucumber'
gem 'page-object'
gem 'rspec'
gem 'ffi'
gem 'httparty'
gem 'sanitize'
gem 'gas_load_tester'
gem 'teamcity_formatter'
gem 'test-unit'
gem 'selenium-webdriver'
gem 'net-http'
gem 'thwait', '~> 0.2.0'
gem 'user_agent_parser', '~> 2.11'
gem 'figaro'